const QUESTIONS = [
  // ===== CELL THEORY & DISCOVERY (PYQ) =====
  {q:"The cell theory was proposed by",opts:["Schleiden and Schwann","Virchow","Robert Hooke","Louis Pasteur"],ans:0,sol:"Cell theory (1838–39) was proposed by Matthias Schleiden (plants) and Theodor Schwann (animals). Virchow later added 'cells arise from pre-existing cells'.",topic:"Cell Theory",year:"PYQ"},
  {q:"Who first observed and described a live cell?",opts:["Robert Brown","Antonie van Leeuwenhoek","Robert Hooke","Theodor Schwann"],ans:1,sol:"Leeuwenhoek used his improved microscope to observe living microorganisms in pond water (1674). Hooke observed dead cork cells in 1665.",topic:"Cell Theory",year:"PYQ"},
  {q:"The term 'protoplasm' was coined by",opts:["Robert Hooke","Johannes Purkinje","Schleiden","Virchow"],ans:1,sol:"Johannes Purkinje (1840) coined the term 'protoplasm' for the living content of cells. It includes cytoplasm + nucleus.",topic:"Cell Theory",year:"PYQ"},
  {q:"Omnis cellula e cellula was stated by",opts:["Schleiden","Schwann","Virchow","Hooke"],ans:2,sol:"Rudolf Virchow (1855) stated 'Omnis cellula e cellula' — all cells arise from pre-existing cells. This completed the cell theory.",topic:"Cell Theory",year:"PYQ"},

  // ===== PROKARYOTIC CELL =====
  {q:"Which of the following is NOT a feature of prokaryotic cells?",opts:["Ribosomes present","Nuclear membrane absent","Cell wall present","Membrane-bound organelles present"],ans:3,sol:"Prokaryotes lack membrane-bound organelles. They have ribosomes (70S), cell wall, and no nuclear membrane. NCERT Class 11 Ch.8",topic:"Prokaryotic Cell",year:"PYQ"},
  {q:"Mycoplasma is unique because it",opts:["Has no ribosomes","Lacks cell wall","Lacks DNA","Has 80S ribosomes"],ans:1,sol:"Mycoplasma lacks cell wall — smallest known living organism. Hence pleomorphic (variable shape) and resistant to penicillin.",topic:"Prokaryotic Cell",year:"PYQ"},
  {q:"Which structure is responsible for conjugation in bacteria?",opts:["Flagella","Pili","Capsule","Mesosome"],ans:1,sol:"Pili (sex pili) facilitate conjugation — transfer of genetic material between bacteria. Flagella = motility. Capsule = protection.",topic:"Prokaryotic Cell",year:"PYQ"},
  {q:"Assertion: Mycoplasma are the smallest living organisms. Reason: They lack cell wall.",opts:["Both A and R true, R explains A","Both true, R does not explain A","A true, R false","A false, R true"],ans:0,sol:"Mycoplasma are smallest self-replicating organisms, lack cell wall (hence pleomorphic). R correctly explains their smallness and flexibility.",topic:"Prokaryotic Cell",year:"Predicted"},
  {q:"Mesosomes in bacteria are associated with",opts:["Protein synthesis","DNA replication and respiration","Cell wall synthesis","Flagella movement"],ans:1,sol:"Mesosomes are infoldings of plasma membrane in bacteria. Associated with DNA replication, respiration, and cell wall formation during division.",topic:"Prokaryotic Cell",year:"PYQ"},
  {q:"70S ribosomes are found in",opts:["Prokaryotes only","Eukaryotes only","Prokaryotes, mitochondria, and chloroplasts","Only in chloroplasts"],ans:2,sol:"70S ribosomes are in prokaryotes, mitochondria (50S+30S subunits), and chloroplasts. Eukaryotic cytoplasm has 80S ribosomes.",topic:"Ribosomes",year:"PYQ"},

  // ===== CELL MEMBRANE =====
  {q:"The fluid mosaic model of plasma membrane was given by",opts:["Watson and Crick","Singer and Nicolson","Davson and Danielli","Robertson"],ans:1,sol:"Singer and Nicolson (1972) proposed the fluid mosaic model — phospholipid bilayer with floating proteins (peripheral + integral).",topic:"Cell Membrane",year:"PYQ"},
  {q:"The unit membrane concept was given by",opts:["Singer","Robertson","Davson","Gorter"],ans:1,sol:"Robertson (1959) proposed the unit membrane model — trilaminar structure (dark-light-dark) seen under electron microscope.",topic:"Cell Membrane",year:"PYQ"},
  {q:"Phospholipid bilayer — which part faces aqueous environment?",opts:["Fatty acid tails","Phosphate heads","Both equally","Neither"],ans:1,sol:"Phospholipids are amphipathic. Hydrophilic phosphate heads face water (extracellular and cytoplasmic). Hydrophobic tails face inward.",topic:"Cell Membrane",year:"PYQ"},
  {q:"In animal cells, cell coat (glycocalyx) is made of",opts:["Cellulose","Glycoproteins and glycolipids","Chitin","Peptidoglycan"],ans:1,sol:"Glycocalyx in animal cells = glycoproteins + glycolipids. Functions in cell recognition, adhesion, immune response, protection.",topic:"Cell Membrane",year:"Predicted"},
  {q:"Plasmolysis occurs when cell is placed in",opts:["Hypotonic solution","Hypertonic solution","Isotonic solution","Pure water"],ans:1,sol:"Plasmolysis: cell in hypertonic solution → water moves out by osmosis → protoplast shrinks away from cell wall.",topic:"Cell Membrane",year:"PYQ"},

  // ===== CELL WALL =====
  {q:"Middle lamella is composed of",opts:["Cellulose","Calcium pectate","Suberin","Lignin"],ans:1,sol:"Middle lamella = calcium pectate. It glues adjacent plant cells together. Pectin is its main component.",topic:"Cell Wall",year:"PYQ"},
  {q:"The primary cell wall of plants is mainly composed of",opts:["Lignin","Cellulose","Chitin","Peptidoglycan"],ans:1,sol:"Primary cell wall = cellulose + hemicellulose + pectin. Secondary wall may contain lignin. Bacterial wall = peptidoglycan.",topic:"Cell Wall",year:"PYQ"},
  {q:"Which of the following is CORRECT about cell wall of fungi?",opts:["Made of cellulose","Made of chitin","Made of peptidoglycan","Absent in fungi"],ans:1,sol:"Fungal cell wall = chitin (polymer of N-acetylglucosamine). Plant = cellulose. Bacteria = peptidoglycan.",topic:"Cell Wall",year:"PYQ"},
  {q:"Plasmodesmata are",opts:["Pores in nuclear membrane","Cytoplasmic connections between plant cells","Cavities in cell wall","Extensions of plasma membrane"],ans:1,sol:"Plasmodesmata are cytoplasmic channels (lined with plasma membrane) connecting adjacent plant cells through cell walls, enabling communication.",topic:"Cell Wall",year:"PYQ"},
  {q:"Protoplast refers to",opts:["Cell without nucleus","Cell without cell wall","Cell without mitochondria","Dead cell"],ans:1,sol:"Protoplast = plant cell with cell wall removed (by cellulase/pectinase enzymes). Used in somatic hybridization and genetic engineering.",topic:"Cell Wall",year:"Predicted"},

  // ===== NUCLEUS =====
  {q:"Which of the following statements about nucleus is CORRECT?",opts:["All cells have nucleus throughout life","RBCs of mammals have large nucleus","Nucleus contains RNA only","Nuclear envelope has two membranes"],ans:3,sol:"Nuclear envelope = two membranes (outer + inner) with nuclear pores. Mature mammalian RBCs have no nucleus. Nucleus has DNA+RNA+proteins.",topic:"Nucleus",year:"PYQ"},
  {q:"Nucleolus is rich in",opts:["DNA only","RNA and proteins","Lipids","Carbohydrates"],ans:1,sol:"Nucleolus is the site of rRNA synthesis and ribosome assembly. Rich in rRNA and proteins. Disappears during cell division.",topic:"Nucleus",year:"PYQ"},
  {q:"The nucleosome consists of DNA wrapped around",opts:["2 copies each of H1, H2A, H2B, H3","2 copies each of H2A, H2B, H3, H4","1 copy of all 5 histones","H1 histone only"],ans:1,sol:"Nucleosome core = 8 histone proteins (2 each of H2A, H2B, H3, H4). H1 is linker histone, sits outside the core particle.",topic:"Nucleus",year:"Predicted"},
  {q:"Heterochromatin is",opts:["Loosely packed, transcriptionally active","Densely packed, transcriptionally inactive","Loosely packed, inactive","Densely packed, active"],ans:1,sol:"Heterochromatin = densely packed, gene-poor, transcriptionally inactive. Euchromatin = loosely packed, active. Barr body = condensed heterochromatin.",topic:"Nucleus",year:"PYQ"},
  {q:"The site of ribosome synthesis is",opts:["Cytoplasm","Nucleolus","Smooth ER","Golgi body"],ans:1,sol:"Nucleolus is the site of rRNA synthesis and ribosome subunit assembly. Ribosomal proteins made in cytoplasm and imported to nucleolus.",topic:"Nucleus",year:"PYQ"},
  {q:"Nucleosome packaging level from DNA to chromosome:",opts:["DNA→Nucleosome→30nm fiber→Looped domains→Chromosome","DNA→Chromosome→Nucleosome→Chromatin","DNA→Looped domains→Nucleosome→Chromosome","Random condensation"],ans:0,sol:"Hierarchical packaging: DNA (2nm) → Nucleosome (10nm) → 30nm fiber → Looped domains (300nm) → 700nm → Metaphase chromosome (1400nm).",topic:"Nucleus",year:"Predicted"},

  // ===== MITOCHONDRIA =====
  {q:"Which organelle is called the 'powerhouse of the cell'?",opts:["Nucleus","Ribosome","Mitochondria","Golgi apparatus"],ans:2,sol:"Mitochondria synthesize ATP via oxidative phosphorylation — hence 'powerhouse'. Contain their own circular DNA and 70S ribosomes.",topic:"Mitochondria",year:"PYQ"},
  {q:"Cristae are found in",opts:["Chloroplasts","Mitochondria","Nucleus","Endoplasmic reticulum"],ans:1,sol:"Cristae are infoldings of the inner mitochondrial membrane. They increase surface area for ATP synthesis (respiratory chain proteins).",topic:"Mitochondria",year:"PYQ"},
  {q:"Which of the following is a semi-autonomous organelle?",opts:["Lysosome","Ribosome","Mitochondria","Golgi body"],ans:2,sol:"Mitochondria (and chloroplasts) are semi-autonomous — have their own circular DNA and 70S ribosomes, can self-replicate to some extent.",topic:"Mitochondria",year:"PYQ"},
  {q:"Which statement is INCORRECT about mitochondria?",opts:["They have circular DNA","Outer membrane is permeable","They contain 80S ribosomes","Inner membrane forms cristae"],ans:2,sol:"Mitochondria have 70S ribosomes (not 80S). Outer membrane is permeable, inner has cristae, DNA is circular like bacteria.",topic:"Mitochondria",year:"Predicted"},
  {q:"Which of the following is a feature of inner mitochondrial membrane?",opts:["Permeable to all molecules","Contains ATP synthase","Lacks proteins","Smooth without folds"],ans:1,sol:"Inner mitochondrial membrane contains ATP synthase (Complex V), respiratory chain complexes. It is impermeable and forms cristae.",topic:"Mitochondria",year:"PYQ"},
  {q:"Endosymbiont theory proposes that mitochondria originated from",opts:["Nucleus","Endoplasmic reticulum","Engulfed aerobic bacteria","Golgi apparatus"],ans:2,sol:"Lynn Margulis proposed endosymbiont theory — mitochondria from engulfed alpha-proteobacteria. Evidence: circular DNA, 70S ribosomes, double membrane.",topic:"Mitochondria",year:"Predicted"},

  // ===== CHLOROPLAST =====
  {q:"Thylakoids are found in",opts:["Mitochondria","Chloroplasts","Lysosomes","Nucleus"],ans:1,sol:"Thylakoids are flattened disc-like membrane sacs in chloroplasts arranged in stacks called grana. Site of light-dependent reactions.",topic:"Chloroplast",year:"Predicted"},
  {q:"Which of the following organelles is associated with photorespiration?",opts:["Mitochondria only","Chloroplasts only","Peroxisomes, chloroplasts, mitochondria","Peroxisomes only"],ans:2,sol:"Photorespiration involves all three: chloroplasts (RuBisCO oxygenase reaction), peroxisomes (glycolate oxidation), mitochondria (decarboxylation).",topic:"Chloroplast",year:"Predicted"},

  // ===== ENDOPLASMIC RETICULUM =====
  {q:"Which type of endoplasmic reticulum is continuous with nuclear envelope?",opts:["Smooth ER","Rough ER","Both equally","Neither"],ans:1,sol:"Rough ER (with ribosomes) is continuous with the outer nuclear membrane. Important for co-translational secretory protein synthesis.",topic:"Endoplasmic Reticulum",year:"PYQ"},
  {q:"Which of the following is a correct statement about smooth ER?",opts:["It has ribosomes","It synthesizes proteins","It is involved in lipid synthesis","It forms nuclear envelope"],ans:2,sol:"Smooth ER lacks ribosomes. Involved in lipid/steroid synthesis, detoxification (in liver), and calcium storage (in muscle cells).",topic:"Endoplasmic Reticulum",year:"Predicted"},
  {q:"Signal recognition particle (SRP) is involved in",opts:["DNA replication","Protein targeting to ER","Lipid synthesis","ATP synthesis"],ans:1,sol:"SRP recognizes the signal peptide on a ribosome and directs the ribosome to rough ER for co-translational protein insertion/secretion.",topic:"Endoplasmic Reticulum",year:"Predicted"},
  {q:"Which organelle is involved in detoxification in liver cells?",opts:["Lysosome","Smooth ER","Rough ER","Peroxisome"],ans:1,sol:"Smooth ER in liver hepatocytes contains cytochrome P450 enzymes for drug/alcohol detoxification. Peroxisomes also contribute.",topic:"Endoplasmic Reticulum",year:"Predicted"},

  // ===== GOLGI APPARATUS =====
  {q:"Lysosomes are formed by",opts:["Mitochondria","Rough ER","Golgi apparatus","Smooth ER"],ans:2,sol:"Lysosomes are formed by Golgi apparatus. Hydrolytic enzymes are synthesized in rough ER, sent to Golgi, then packaged into lysosomes.",topic:"Golgi Apparatus",year:"PYQ"},
  {q:"The 'cis' face of Golgi apparatus faces",opts:["Plasma membrane","ER","Nucleus","Vacuole"],ans:1,sol:"Cis face of Golgi = receiving face, faces endoplasmic reticulum. Trans face = secretory/maturing face, faces plasma membrane.",topic:"Golgi Apparatus",year:"PYQ"},
  {q:"Which of the following is NOT a function of Golgi apparatus?",opts:["Glycosylation of proteins","Formation of lysosomes","ATP synthesis","Secretion and packaging"],ans:2,sol:"Golgi: modifies (glycosylation), packages, sorts proteins/lipids, forms lysosomes, secretes. ATP synthesis occurs in mitochondria.",topic:"Golgi Apparatus",year:"Predicted"},

  // ===== LYSOSOMES =====
  {q:"Which cell organelle is responsible for intracellular digestion?",opts:["Peroxisome","Lysosome","Vacuole","Glyoxysome"],ans:1,sol:"Lysosomes contain 40+ hydrolytic enzymes (proteases, lipases, nucleases) active at pH ~5 for intracellular digestion (autophagy).",topic:"Lysosomes",year:"PYQ"},
  {q:"The 'suicidal bags' of the cell are",opts:["Mitochondria","Lysosomes","Peroxisomes","Vacuoles"],ans:1,sol:"Lysosomes called 'suicidal bags' — contain hydrolytic enzymes that can digest cell contents if membrane ruptures (autolysis). Named by de Duve.",topic:"Lysosomes",year:"PYQ"},

  // ===== VACUOLES =====
  {q:"Tonoplast is the membrane surrounding",opts:["Chloroplast","Central vacuole","Mitochondria","Nucleus"],ans:1,sol:"Tonoplast = membrane of central vacuole in plant cells. Maintains turgor pressure, stores ions, metabolites, and pigments.",topic:"Vacuoles",year:"Predicted"},
  {q:"Stomata opening and closing involves",opts:["Nucleus","Mitochondria","Central vacuole of guard cells","Chloroplast only"],ans:2,sol:"Guard cell vacuole changes turgor — ion (K⁺) accumulation causes water entry (stomata open), exit closes them.",topic:"Vacuoles",year:"Predicted"},

  // ===== RIBOSOMES =====
  {q:"Which of the following correctly describes a eukaryotic ribosome?",opts:["70S — 30S+50S subunits","80S — 40S+60S subunits","80S — 30S+50S","70S — 40S+60S"],ans:1,sol:"Eukaryotic ribosome: 80S = 40S (small) + 60S (large) subunits. Prokaryotic: 70S = 30S + 50S. Mitochondrial = 70S.",topic:"Ribosomes",year:"PYQ"},

  // ===== CENTRIOLES & CYTOSKELETON =====
  {q:"Centrioles are absent in",opts:["Animal cells","Higher plant cells","Algae","Fungi"],ans:1,sol:"Higher plant cells (angiosperms) lack centrioles. They form spindle without asters — anastral spindle. Lower plants, algae, fungi may have them.",topic:"Centrioles",year:"PYQ"},
  {q:"Which of the following is INCORRECT about centrioles?",opts:["Made of tubulin","Show 9+0 arrangement","Show 9+2 arrangement","Involved in spindle formation"],ans:2,sol:"Centrioles show 9+0 triplet arrangement (9 triplets, no central pair). Cilia/flagella show 9+2 arrangement. Both made of tubulin.",topic:"Centrioles",year:"PYQ"},
  {q:"Microtubules are made of",opts:["Actin","Tubulin","Myosin","Keratin"],ans:1,sol:"Microtubules = polymerized tubulin proteins (alpha and beta tubulin dimers). Part of cytoskeleton, spindle fibers, cilia, flagella.",topic:"Cytoskeleton",year:"PYQ"},
  {q:"Which of the following is NOT a component of cytoskeleton?",opts:["Microtubules","Microfilaments","Intermediate filaments","Microvilli"],ans:3,sol:"Cytoskeleton = microtubules + microfilaments (actin) + intermediate filaments. Microvilli are cell surface projections, not cytoskeletal elements.",topic:"Cytoskeleton",year:"Predicted"},
  {q:"Streaming of cytoplasm (cyclosis) is associated with which cytoskeletal element?",opts:["Microtubules","Actin microfilaments","Intermediate filaments","Collagen fibers"],ans:1,sol:"Cytoplasmic streaming (cyclosis) is driven by myosin motors moving along actin filaments. Seen in plant cells and Amoeba.",topic:"Cytoskeleton",year:"Predicted"},

  // ===== CHROMOSOMES =====
  {q:"The centromere is the region where",opts:["DNA replication begins","Spindle fibres attach","Crossing over occurs","RNA is synthesized"],ans:1,sol:"Spindle fibres (kinetochore fibres) attach to centromere via kinetochore proteins during cell division to pull chromatids apart.",topic:"Chromosomes",year:"PYQ"},
  {q:"Acrocentric chromosome has centromere at",opts:["Middle","Sub-terminal position","Terminal end","Both ends"],ans:1,sol:"Acrocentric = centromere near (not at) end → sub-terminal. Metacentric = middle, Telocentric = terminal. SAT chromosomes are acrocentric.",topic:"Chromosomes",year:"PYQ"},
  {q:"Which of the following is CORRECT about eukaryotic chromosome?",opts:["It has only DNA","It has DNA + RNA + proteins","It is circular like prokaryotes","It lacks histones"],ans:1,sol:"Eukaryotic chromosomes = DNA + histone proteins + non-histone proteins + some RNA. Linear structure, not circular.",topic:"Chromosomes",year:"PYQ"},
  {q:"Constriction in chromosome other than centromere is called",opts:["Centromere","Secondary constriction","Telomere","Kinetochore"],ans:1,sol:"Secondary constriction = NOR (nucleolar organizer region) where rDNA is located and nucleolus forms. Found on SAT chromosomes.",topic:"Chromosomes",year:"PYQ"},
  {q:"Lampbrush chromosomes are seen in",opts:["Oocytes of amphibians","Salivary glands","Liver cells","Neurons"],ans:0,sol:"Lampbrush chromosomes occur in oocytes (eggs) of amphibians during prolonged diplotene stage — active transcription creates loops.",topic:"Chromosomes",year:"Predicted"},
  {q:"Polytene chromosomes are found in",opts:["Oocytes","Salivary glands of Drosophila","Bacteria","During meiosis"],ans:1,sol:"Polytene chromosomes found in salivary glands of Drosophila — result of DNA replication without cell division (endomitosis). Show puffing.",topic:"Chromosomes",year:"Predicted"},
  {q:"Balbiani rings represent",opts:["Inactive chromatin","Active gene transcription sites","Heterochromatin","Centromere regions"],ans:1,sol:"Puffs/Balbiani rings in polytene chromosomes = regions of active RNA synthesis. Indicate active gene expression. Swell with RNA.",topic:"Chromosomes",year:"Predicted"},
  {q:"Telomeres function to",opts:["Initiate replication","Protect chromosome ends from degradation","Attach to spindle","Store genetic info"],ans:1,sol:"Telomeres (TTAGGG repeats in humans) cap chromosome ends, preventing degradation, end-to-end fusion, and solve end-replication problem.",topic:"Chromosomes",year:"Predicted"},

  // ===== CELL CYCLE =====
  {q:"The S phase of cell cycle is associated with",opts:["Cell growth","DNA replication","Spindle formation","Cytokinesis"],ans:1,sol:"S (Synthesis) phase: DNA replication occurs. DNA content doubles from 2C to 4C. Histone synthesis also occurs in S phase.",topic:"Cell Cycle",year:"PYQ"},
  {q:"The correct sequence of cell cycle phases is",opts:["G1→S→G2→M","S→G1→G2→M","G1→G2→S→M","M→S→G1→G2"],ans:0,sol:"Interphase: G1 (cell growth) → S (DNA synthesis) → G2 (prep for division) → M phase (mitosis/meiosis). G0 = quiescent phase.",topic:"Cell Cycle",year:"PYQ"},
  {q:"G0 phase cells are",opts:["Actively dividing","Quiescent/non-dividing","In S phase","In mitosis"],ans:1,sol:"G0 = quiescent phase. Cells exit cell cycle and don't divide. Some can re-enter cycle under stimulation. E.g. liver cells, neurons.",topic:"Cell Cycle",year:"PYQ"},
  {q:"Apoptosis is",opts:["Cell division","Programmed cell death","Accidental cell death","Cell swelling"],ans:1,sol:"Apoptosis = programmed cell death. Orderly, energy-dependent (caspase-mediated) process. Important in development and immune response. ≠ necrosis.",topic:"Cell Cycle",year:"PYQ"},
  {q:"In which phase does DNA content become 4N?",opts:["After G1","After S phase","After G2","At metaphase"],ans:1,sol:"DNA doubles during S phase: 2N→4N DNA content. Chromosome number remains 2N. 4N DNA content maintained through G2 and M phase.",topic:"Cell Cycle",year:"Predicted"},
  {q:"The enzyme responsible for DNA unwinding during replication is",opts:["DNA ligase","Primase","Helicase","Topoisomerase"],ans:2,sol:"Helicase breaks hydrogen bonds between base pairs to unwind DNA at replication fork. Topoisomerase relieves torsional tension ahead.",topic:"Cell Cycle",year:"Predicted"},
  {q:"The enzyme that joins Okazaki fragments is",opts:["Helicase","Primase","DNA ligase","DNA polymerase I"],ans:2,sol:"DNA ligase joins Okazaki fragments on lagging strand by forming phosphodiester bonds between them. Also seals nicks in DNA.",topic:"Cell Cycle",year:"Predicted"},
  {q:"Which enzyme relaxes supercoiling ahead of replication fork?",opts:["Helicase","Topoisomerase","Ligase","Primase"],ans:1,sol:"Topoisomerase II cuts and rejoins DNA to relieve positive supercoils (torsional stress) created ahead of replication fork.",topic:"Cell Cycle",year:"Predicted"},
  {q:"Restriction point in cell cycle is present in",opts:["G1 phase","S phase","G2 phase","M phase"],ans:0,sol:"Restriction point (R point) in G1: cell commits to division if growth factors present. Key checkpoint before S phase entry.",topic:"Cell Cycle",year:"Predicted"},
  {q:"G1/S checkpoint prevents entry into S phase if",opts:["Cell is too large","DNA is damaged","Spindle is incomplete","Cytoplasm is undivided"],ans:1,sol:"G1/S checkpoint: p53 activates p21 (CDK inhibitor). If DNA damage detected, cell arrested in G1 for repair or apoptosis.",topic:"Cell Cycle",year:"Predicted"},
  {q:"p53 protein is a",opts:["Oncogene product","Tumor suppressor protein","Structural protein","Transport protein"],ans:1,sol:"p53 = tumor suppressor protein. Monitors DNA damage, activates repair, triggers apoptosis if irreparable. Called 'guardian of genome'.",topic:"Cell Cycle",year:"Predicted"},

  // ===== MITOSIS =====
  {q:"During which phase are chromosomes most clearly visible for karyotyping?",opts:["Prophase","Metaphase","Anaphase","Telophase"],ans:1,sol:"Metaphase: chromosomes align at equatorial plate, maximally condensed (1–10 μm). Best phase for karyotyping and chromosome studies.",topic:"Mitosis",year:"PYQ"},
  {q:"Which phase of mitosis is longest?",opts:["Metaphase","Anaphase","Prophase","Telophase"],ans:2,sol:"Prophase is the longest phase of mitosis — chromosome condensation, centriole duplication, spindle formation all take more time.",topic:"Mitosis",year:"PYQ"},
  {q:"Karyokinesis refers to",opts:["Division of cytoplasm","Division of nucleus","DNA replication","Chromosome condensation"],ans:1,sol:"Karyokinesis = nuclear division (division of nucleus). Cytokinesis = cytoplasmic division. Both together complete cell division.",topic:"Mitosis",year:"PYQ"},
  {q:"The spindle fibers are made up of",opts:["Actin filaments","Tubulin protein","Intermediate filaments","Collagen"],ans:1,sol:"Spindle fibers = microtubules (tubulin polymers). Kinetochore fibers attach to centromeres. Polar fibers overlap at equatorial plane.",topic:"Mitosis",year:"PYQ"},
  {q:"Cytokinesis in plant cells occurs by",opts:["Cleavage furrow","Cell plate formation","Spindle elongation","Fragmentation"],ans:1,sol:"Plant cells form a cell plate (phragmoplast) at center during telophase, expanding outward. Animals use cleavage furrow (actomyosin ring).",topic:"Mitosis",year:"PYQ"},
  {q:"Cell plate formation starts at",opts:["Periphery and moves inward","Center and moves outward","Both ends simultaneously","Top of cell"],ans:1,sol:"Cell plate forms from Golgi vesicles accumulating at equatorial plane center (phragmoplast), expanding outward to meet cell walls.",topic:"Mitosis",year:"PYQ"},
  {q:"The condensin protein complex functions in",opts:["DNA replication","Chromosome condensation","Spindle formation","Cytokinesis"],ans:1,sol:"Condensin complexes (SMC proteins) drive chromosome condensation during prophase. Cohesin holds sister chromatids together.",topic:"Mitosis",year:"Predicted"},
  {q:"MTOC stands for",opts:["Mitochondrial outer membrane complex","Microtubule organizing center","Membrane transport outer channel","Micro transfer organelle complex"],ans:1,sol:"MTOC = Microtubule Organizing Center. Centrioles form MTOC (with aster) in animals. Absent in higher plant cells (anastral spindle).",topic:"Mitosis",year:"Predicted"},

  // ===== MEIOSIS =====
  {q:"Synaptonemal complex is formed during",opts:["Leptotene","Zygotene","Pachytene","Diplotene"],ans:1,sol:"Synaptonemal complex (protein structure) forms during zygotene when homologous chromosomes pair (synapsis). Complete by pachytene.",topic:"Meiosis",year:"PYQ"},
  {q:"Crossing over occurs during",opts:["Leptotene","Zygotene","Pachytene","Diplotene"],ans:2,sol:"Crossing over (exchange of DNA segments between non-sister chromatids of homologous chromosomes) occurs at pachytene stage of meiosis I.",topic:"Meiosis",year:"PYQ"},
  {q:"Chiasmata are seen during",opts:["Leptotene","Zygotene","Diplotene","Diakinesis"],ans:2,sol:"Chiasmata (X-shaped structures at crossover points) first become visible in diplotene when bivalents begin to separate.",topic:"Meiosis",year:"PYQ"},
  {q:"In meiosis II, separation of _____ occurs",opts:["Homologous chromosomes","Sister chromatids","Bivalents","Tetrads"],ans:1,sol:"Meiosis I: homologous chromosomes separate (reductional). Meiosis II: sister chromatids separate (equational — similar to mitosis).",topic:"Meiosis",year:"PYQ"},
  {q:"Which of the following is CORRECT about meiosis?",opts:["It occurs in somatic cells","It results in 4 diploid cells","Crossing over increases genetic variation","It has only one division"],ans:2,sol:"Crossing over in pachytene of meiosis I shuffles alleles between homologs — major source of genetic variation in sexually reproducing organisms.",topic:"Meiosis",year:"PYQ"},
  {q:"Which represents correct ploidy after fertilization?",opts:["n","2n","3n","4n"],ans:1,sol:"Fertilization: n (egg) + n (sperm) = 2n (zygote). Diploid state is restored. Meiosis in reproductive organs reduces to n.",topic:"Meiosis",year:"PYQ"},

  // ===== ADDITIONAL ORGANELLES =====
  {q:"Glyoxysomes are found in",opts:["Animal cells","Germinating fatty seeds","Liver cells","Muscle cells"],ans:1,sol:"Glyoxysomes (specialized peroxisomes) are in germinating fatty seeds — convert fats to sugars via glyoxylate cycle. Not in animals.",topic:"Cell Organelles",year:"Predicted"},
  {q:"Peroxisomes detoxify harmful compounds using",opts:["Hydrogen peroxide","Catalase enzyme","Lysosomal acid","Protease"],ans:1,sol:"Peroxisomes use catalase to decompose H₂O₂ (produced during fatty acid oxidation and detox reactions) → H₂O + O₂. Prevent cellular damage.",topic:"Cell Organelles",year:"Predicted"},
  {q:"Which of the following correctly matches organelle to its function?",opts:["Ribosome — lipid synthesis","Mitochondria — protein synthesis","Chloroplast — photosynthesis","Lysosome — ATP production"],ans:2,sol:"Chloroplast = photosynthesis. Ribosome = protein synthesis. Mitochondria = ATP. Lysosome = digestion.",topic:"Cell Organelles",year:"PYQ"},
  {q:"Undulipodia are",opts:["Bacterial flagella","Eukaryotic cilia and flagella","Pili","Fimbriae"],ans:1,sol:"Undulipodia = eukaryotic cilia and flagella (9+2 microtubule arrangement). Bacterial flagella are structurally different (no tubulin, no 9+2).",topic:"Cell Organelles",year:"Predicted"},
  {q:"Which of the following has the largest cell?",opts:["Bacterium","Ostrich egg","Human ovum","Nerve cell"],ans:1,sol:"The ostrich egg is the largest known single cell (~15 cm diameter). The yolk constitutes the actual cell. Human ovum ~0.1mm.",topic:"Cell Size",year:"PYQ"},
  {q:"The nuclear pore complex allows passage of",opts:["Small molecules only","Large molecules by active transport","Nothing","Only lipids"],ans:1,sol:"Nuclear pore complex (NPC) — ~120 MDa protein structure. Controls nucleo-cytoplasmic transport. Allows active transport of proteins, mRNA.",topic:"Nucleus",year:"Predicted"},
  {q:"Which phase shows DNA content 4N but chromosome number 2N?",opts:["G1","G2","After meiosis I","Anaphase of mitosis"],ans:1,sol:"G2 phase: DNA replicated (4N content) but chromosomes not yet separated (2N chromosome count, as sister chromatids are still joined).",topic:"Cell Cycle",year:"Predicted"},
  {q:"Which of the following is the site of fatty acid synthesis?",opts:["Mitochondria","Smooth ER","Rough ER","Nucleus"],ans:1,sol:"Smooth ER is the major site of fatty acid and phospholipid synthesis in eukaryotic cells (fatty acid synthase complex).",topic:"Endoplasmic Reticulum",year:"Predicted"},
  {q:"Chromatin remodeling is important for",opts:["Cell wall synthesis","Gene expression regulation","Ribosome assembly","ATP production"],ans:1,sol:"Chromatin remodeling (histone modification, DNA methylation, nucleosome repositioning) controls gene accessibility and gene expression.",topic:"Nucleus",year:"Predicted"},
  {q:"Assertion: Cell division in bacteria is amitotic. Reason: Bacteria are prokaryotes.",opts:["Both true, R explains A","Both true, R does not explain A","A true R false","Both false"],ans:0,sol:"Bacteria divide by binary fission (amitotic). Being prokaryotes, they lack organized spindle and membrane-bound nucleus. R correctly explains A.",topic:"Prokaryotic Cell",year:"Predicted"},
];
